services:
  framepack-eichi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=Asia/Shanghai
    ports:
      - "7862:7862"
    volumes:
      - ./data:/app/framepack/data
      - D:\home\models\hf_download:/app/framepack/hf_download
      - ./outputs:/app/framepack/outputs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - http_proxy=http://192.168.1.5:10808
      - https_proxy=http://192.168.1.5:10808
    devices:
      - nvidia.com/gpu=all
    security_opt:
       - label=disable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: ["--lang", "zh-tw"]  # Options: "en", "ja", "zh-tw"
